/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlRegistrarse;

/**
 *
 * @author Fernando
 */
public class VistaRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form AgregaUsuario
     */
    public VistaRegistrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jTCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTNacimiento = new javax.swing.JTextField();
        jTCelular = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jTDireccion = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aviones temáticos. 1192015.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gg.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(415, 665));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Registrar Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 140, 24);

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(194, 499, 106, 40);

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(50, 500, 94, 40);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(7, 66, 70, 19);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 90, 19);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 158, 70, 19);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Apellidos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 204, 80, 19);

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Correo Electrónico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(11, 250, 130, 19);

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Nacimiento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 130, 19);
        getContentPane().add(jTUsuario);
        jTUsuario.setBounds(160, 60, 160, 30);
        getContentPane().add(jTNombre);
        jTNombre.setBounds(160, 150, 160, 30);

        jTApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTApellidos);
        jTApellidos.setBounds(160, 200, 240, 30);
        getContentPane().add(jTCorreo);
        jTCorreo.setBounds(159, 244, 240, 30);

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Dirección");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 340, 80, 19);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("Telefono Trabajo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 400, 120, 19);

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Celular");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 440, 70, 19);
        getContentPane().add(jTNacimiento);
        jTNacimiento.setBounds(160, 290, 180, 30);
        getContentPane().add(jTCelular);
        jTCelular.setBounds(160, 430, 190, 30);

        jPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword1);
        jPassword1.setBounds(160, 100, 160, 30);
        getContentPane().add(jTDireccion);
        jTDireccion.setBounds(160, 340, 180, 30);
        getContentPane().add(jTTelefono);
        jTTelefono.setBounds(160, 390, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidosActionPerformed

    private void jPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrarse().setVisible(true);
            }
        });
    }
    ControlRegistrarse registrarse;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTNacimiento;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables

    public void setController(ControlRegistrarse registrarse) {

        this.registrarse = registrarse;

        btnCancelar.addActionListener(registrarse);
        btnGuardar.addActionListener(registrarse);
        jPassword1.addActionListener(registrarse);
        jTApellidos.addActionListener(registrarse);
        jTCelular.addActionListener(registrarse);
        jTCorreo.addActionListener(registrarse);
        jTDireccion.addActionListener(registrarse);
        jTNacimiento.addActionListener(registrarse);
        jTNombre.addActionListener(registrarse);
        jTTelefono.addActionListener(registrarse);
        jTUsuario.addActionListener(registrarse);
    }
}

     
    // End of variables declaration                   
