/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Fernando
 */
public class VistaAsientos extends javax.swing.JFrame {

    /**
     * Creates new form VistaAsinetos
     */
    public VistaAsientos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1a = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btn1b = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        btn1c = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        btn1d = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 580));
        getContentPane().setLayout(null);

        btn1a.setText("1A");
        getContentPane().add(btn1a);
        btn1a.setBounds(24, 127, 45, 30);

        jButton2.setText("2A");
        getContentPane().add(jButton2);
        jButton2.setBounds(24, 163, 45, 30);

        jButton3.setText("3A");
        getContentPane().add(jButton3);
        jButton3.setBounds(24, 199, 45, 30);

        jButton4.setText("5A");
        getContentPane().add(jButton4);
        jButton4.setBounds(24, 271, 45, 30);

        jButton5.setText("4A");
        getContentPane().add(jButton5);
        jButton5.setBounds(24, 235, 45, 30);

        jButton6.setText("6A");
        getContentPane().add(jButton6);
        jButton6.setBounds(24, 307, 45, 30);

        jButton7.setText("7A");
        getContentPane().add(jButton7);
        jButton7.setBounds(24, 343, 45, 30);

        jButton8.setText("8A");
        getContentPane().add(jButton8);
        jButton8.setBounds(24, 379, 45, 30);

        jButton9.setText("9A");
        getContentPane().add(jButton9);
        jButton9.setBounds(24, 415, 45, 30);

        jButton10.setText("2B");
        getContentPane().add(jButton10);
        jButton10.setBounds(72, 163, 45, 30);

        btn1b.setText("1B");
        getContentPane().add(btn1b);
        btn1b.setBounds(72, 127, 45, 30);

        jButton12.setText("3B");
        getContentPane().add(jButton12);
        jButton12.setBounds(72, 199, 45, 30);

        jButton13.setText("4B");
        getContentPane().add(jButton13);
        jButton13.setBounds(72, 235, 45, 30);

        jButton14.setText("5B");
        getContentPane().add(jButton14);
        jButton14.setBounds(72, 271, 45, 30);

        jButton15.setText("6B");
        getContentPane().add(jButton15);
        jButton15.setBounds(72, 307, 45, 30);

        jButton16.setText("7B");
        getContentPane().add(jButton16);
        jButton16.setBounds(72, 343, 45, 30);

        jButton17.setText("8B");
        getContentPane().add(jButton17);
        jButton17.setBounds(72, 379, 45, 30);

        jButton18.setText("9B");
        getContentPane().add(jButton18);
        jButton18.setBounds(72, 415, 45, 30);

        jButton19.setText("4C");
        getContentPane().add(jButton19);
        jButton19.setBounds(121, 235, 45, 30);

        jButton20.setText("5C");
        getContentPane().add(jButton20);
        jButton20.setBounds(121, 271, 45, 30);

        jButton21.setText("6C");
        getContentPane().add(jButton21);
        jButton21.setBounds(121, 307, 45, 30);

        jButton22.setText("7C");
        getContentPane().add(jButton22);
        jButton22.setBounds(121, 343, 45, 30);

        jButton23.setText("8C");
        getContentPane().add(jButton23);
        jButton23.setBounds(121, 379, 45, 30);

        jButton24.setText("9C");
        getContentPane().add(jButton24);
        jButton24.setBounds(121, 415, 45, 30);

        jButton25.setText("2C");
        getContentPane().add(jButton25);
        jButton25.setBounds(121, 163, 45, 30);

        btn1c.setText("1C");
        getContentPane().add(btn1c);
        btn1c.setBounds(121, 127, 45, 30);

        jButton27.setText("3C");
        getContentPane().add(jButton27);
        jButton27.setBounds(121, 199, 45, 30);

        jButton28.setText("2D");
        getContentPane().add(jButton28);
        jButton28.setBounds(207, 163, 45, 30);

        jButton29.setText("4E");
        getContentPane().add(jButton29);
        jButton29.setBounds(257, 235, 45, 30);

        jButton30.setText("5E");
        getContentPane().add(jButton30);
        jButton30.setBounds(257, 271, 45, 30);

        jButton31.setText("6E");
        getContentPane().add(jButton31);
        jButton31.setBounds(257, 307, 45, 30);

        jButton32.setText("7E");
        getContentPane().add(jButton32);
        jButton32.setBounds(257, 343, 45, 30);

        jButton33.setText("8E");
        getContentPane().add(jButton33);
        jButton33.setBounds(257, 379, 45, 30);

        jButton34.setText("9E");
        getContentPane().add(jButton34);
        jButton34.setBounds(257, 415, 45, 30);

        jButton35.setText("4F");
        getContentPane().add(jButton35);
        jButton35.setBounds(306, 235, 45, 30);

        jButton36.setText("5F");
        getContentPane().add(jButton36);
        jButton36.setBounds(306, 271, 45, 30);

        jButton37.setText("6F");
        getContentPane().add(jButton37);
        jButton37.setBounds(306, 307, 45, 30);

        jButton38.setText("7F");
        getContentPane().add(jButton38);
        jButton38.setBounds(306, 343, 45, 30);

        jButton39.setText("8F");
        getContentPane().add(jButton39);
        jButton39.setBounds(306, 379, 45, 30);

        btn1d.setText("1D");
        getContentPane().add(btn1d);
        btn1d.setBounds(207, 127, 45, 30);

        jButton41.setText("9F");
        getContentPane().add(jButton41);
        jButton41.setBounds(306, 415, 45, 30);

        jButton42.setText("3D");
        getContentPane().add(jButton42);
        jButton42.setBounds(207, 199, 45, 30);

        jButton43.setText("2F");
        getContentPane().add(jButton43);
        jButton43.setBounds(306, 163, 45, 30);

        jButton44.setText("5D");
        getContentPane().add(jButton44);
        jButton44.setBounds(207, 271, 45, 30);

        jButton45.setText("1F");
        getContentPane().add(jButton45);
        jButton45.setBounds(306, 127, 45, 30);

        jButton46.setText("4D");
        getContentPane().add(jButton46);
        jButton46.setBounds(207, 235, 45, 30);

        jButton47.setText("3F");
        getContentPane().add(jButton47);
        jButton47.setBounds(306, 199, 45, 30);

        jButton48.setText("6D");
        getContentPane().add(jButton48);
        jButton48.setBounds(207, 307, 45, 30);

        jButton49.setText("7D");
        getContentPane().add(jButton49);
        jButton49.setBounds(207, 343, 45, 30);

        jButton50.setText("8D");
        getContentPane().add(jButton50);
        jButton50.setBounds(207, 379, 45, 30);

        jButton51.setText("9D");
        getContentPane().add(jButton51);
        jButton51.setBounds(207, 415, 45, 30);

        jButton52.setText("2E");
        getContentPane().add(jButton52);
        jButton52.setBounds(257, 163, 45, 30);

        jButton53.setText("1E");
        getContentPane().add(jButton53);
        jButton53.setBounds(257, 127, 45, 30);

        jButton54.setText("3E");
        getContentPane().add(jButton54);
        jButton54.setBounds(257, 199, 45, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(440, 140, 132, 20);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad de Asinrtos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 110, 132, 19);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Numero de Asientos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 180, 127, 19);

        jScrollPane1.setViewportView(jTextField2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 220, 127, 22);

        jButton1.setText("Aceptar");
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 400, 80, 30);

        jButton11.setText("Cancelar");
        getContentPane().add(jButton11);
        jButton11.setBounds(520, 400, 90, 30);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 320, 32, 19);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(440, 320, 120, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(560, 10, 130, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/las-mejores-y-peores-aerolineas-del-mundo-reveladas.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 730, 590);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAsientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1a;
    private javax.swing.JButton btn1b;
    private javax.swing.JButton btn1c;
    private javax.swing.JButton btn1d;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
